# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'cucumber-ado-testplans-sync'
description: 'Cucumber to Azure DevOps TestPlans Synchronization'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'bell'
  color: 'green'
inputs:
  ado-pat:
    description: 'Azure DevOps PAT'
    required: true
  ado-org-id:
    description: 'ADO Org URL'
    required: true
  project-id:
    description: 'ADO Project ID'
    required: true
  plan-id:
    description: 'ADO Plan ID'
    required: true
  suite-id:
    description: 'ADO Suite ID'
    required: false
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ado-pat }}
    - ${{ inputs.ado-org-id }}
    - ${{ inputs.project-id }}
    - ${{ inputs.plan-id }}
    - ${{ inputs.suite-id }}